# Site settings
title: Chartophile
email: eben@chartophile.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "http://ebendennis.github.io/blog" # the subpath of your site, e.g. /blog/
url: "http://ebendennis.github.io" # the base hostname & protocol for your site
twitter_username: ebendennis
github_username:  ebendennis

# Build settings
markdown: kramdown

# Prose settings
prose:
  rooturl: '_posts'
  siteurl: 'http://ebendennis.github.io'
  relativeLinks: ''
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
